-- MySQL Script generated by MySQL Workbench
-- Mon May 27 12:34:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Partner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Partner` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`));


-- -----------------------------------------------------
-- Table `mydb`.`LegalForm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LegalForm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LegalForm` (
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`title`));


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `siret` CHAR(14) NOT NULL,
  `companyName` VARCHAR(255) NOT NULL,
  `legalFormTitle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`siret`),
  INDEX `idx_legalFormTitle` (`legalFormTitle` ASC) VISIBLE,
  CONSTRAINT `fk_client_legalForm`
    FOREIGN KEY (`legalFormTitle`)
    REFERENCES `mydb`.`LegalForm` (`title`));


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`));


-- -----------------------------------------------------
-- Table `mydb`.`AuditPeriod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AuditPeriod` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AuditPeriod` (
  `period_id` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  PRIMARY KEY (`period_id`));


-- -----------------------------------------------------
-- Table `mydb`.`TypeAudit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TypeAudit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TypeAudit` (
  `label` VARCHAR(255) NOT NULL,
  `nomination` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`label`));


-- -----------------------------------------------------
-- Table `mydb`.`MissionAudit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MissionAudit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MissionAudit` (
  `audit_id` INT NOT NULL AUTO_INCREMENT,
  `auditDate` DATE NOT NULL,
  `fee` DECIMAL(10,2) NULL DEFAULT NULL,
  `typeAuditLabel` VARCHAR(255) NOT NULL,
  `period_id` INT NOT NULL,
  `siret` CHAR(14) NOT NULL,
  PRIMARY KEY (`audit_id`),
  INDEX `idx_typeAuditLabel` (`typeAuditLabel` ASC) VISIBLE,
  INDEX `idx_period_id` (`period_id` ASC) VISIBLE,
  INDEX `idx_siret` (`siret` ASC) VISIBLE,
  CONSTRAINT `fk_missionAudit_typeAudit`
    FOREIGN KEY (`typeAuditLabel`)
    REFERENCES `mydb`.`TypeAudit` (`label`),
  CONSTRAINT `fk_missionAudit_period`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`AuditPeriod` (`period_id`),
  CONSTRAINT `fk_missionAudit_client`
    FOREIGN KEY (`siret`)
    REFERENCES `mydb`.`Client` (`siret`));


-- -----------------------------------------------------
-- Table `mydb`.`PartnerMissionAudit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PartnerMissionAudit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PartnerMissionAudit` (
  `partner_id` INT NOT NULL,
  `audit_id` INT NOT NULL,
  PRIMARY KEY (`partner_id`, `audit_id`),
  INDEX `idx_audit_id` (`audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_partnerMissionAudit_partner`
    FOREIGN KEY (`partner_id`)
    REFERENCES `mydb`.`Partner` (`employee_id`),
  CONSTRAINT `fk_partnerMissionAudit_audit`
    FOREIGN KEY (`audit_id`)
    REFERENCES `mydb`.`MissionAudit` (`audit_id`));


-- -----------------------------------------------------
-- Table `mydb`.`ManagerMissionAudit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ManagerMissionAudit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ManagerMissionAudit` (
  `manager_id` INT NOT NULL,
  `audit_id` INT NOT NULL,
  PRIMARY KEY (`manager_id`, `audit_id`),
  INDEX `idx_audit_id` (`audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_managerMissionAudit_manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `mydb`.`Manager` (`employee_id`),
  CONSTRAINT `fk_managerMissionAudit_audit`
    FOREIGN KEY (`audit_id`)
    REFERENCES `mydb`.`MissionAudit` (`audit_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
